using System.Text;

namespace ObjectTreeWalker.SourceGenerator
{
    /// <summary>
    /// Helper class for constructing C# source code files consistently.
    /// Provides methods to generate headers, namespaces, class declarations,
    /// and ensures proper syntax structure.
    /// </summary>
    public class ClassBuilder
    {
        private readonly StringBuilder _sb;

        /// <summary>
        /// Gets the underlying StringBuilder used to construct the class.
        /// </summary>
        public StringBuilder StringBuilder => _sb;

        /// <summary>
        /// Initializes a new instance of the ClassBuilder.
        /// </summary>
        public ClassBuilder()
        {
            _sb = new StringBuilder();
        }

        /// <summary>
        /// Emits the standard file header, including auto-generated comments and compiler pragmas.
        /// </summary>
        public void EmitFileHeader()
        {
            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("#pragma warning disable CS1591");
            _sb.AppendLine("#nullable enable");
        }

        /// <summary>
        /// Starts the namespace declaration.
        /// </summary>
        /// <param name="namespaceName">The name of the namespace.</param>
        public void StartNamespace(string? namespaceName)
        {
            if (namespaceName != null)
            {
                _sb.AppendLine($"namespace {namespaceName}");
                _sb.AppendLine("{");
            }
        }

        /// <summary>
        /// Ends the namespace declaration.
        /// </summary>
        /// <param name="namespaceName">The name of the namespace.</param>
        public void EndNamespace(string? namespaceName)
        {
            if (namespaceName != null)
            {
                _sb.AppendLine("}");
            }
        }

        /// <summary>
        /// Starts a partial class declaration.
        /// </summary>
        /// <param name="className">The name of the class.</param>
        public void StartClass(string className)
        {
            _sb.AppendLine($"    partial class {className}");
            _sb.AppendLine("    {");
        }

        /// <summary>
        /// Ends a class declaration.
        /// </summary>
        public void EndClass()
        {
            _sb.AppendLine("    }");
        }

        /// <summary>
        /// Returns the constructed source code string.
        /// </summary>
        /// <returns>The generated source code string.</returns>
        public override string ToString()
        {
            return _sb.ToString();
        }
    }
}
