#pragma warning disable CS1591
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ObjectTreeWalker.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class DeepCloneGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            var compilationAndClasses = context.CompilationProvider.Combine(provider.Collect());

            context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            foreach (var attributeListSyntax in classDeclaration.AttributeLists)
            {
                foreach (var attributeSyntax in attributeListSyntax.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is IMethodSymbol attributeSymbol)
                    {
                        if (attributeSymbol.ContainingType.ToDisplayString() == "ObjectTreeWalker.DeepCloneableAttribute")
                        {
                            return classDeclaration;
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> classes, SourceProductionContext context)
        {
            if (classes.IsDefaultOrEmpty) return;

            var distinctClasses = classes.Where(c => c != null).Distinct();

            foreach (var classDeclaration in distinctClasses)
            {
                var semanticModel = compilation.GetSemanticModel(classDeclaration!.SyntaxTree);
                var symbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                if (symbol == null) continue;

                var source = ProcessClass(symbol);
                context.AddSource($"{symbol.Name}_DeepClone.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string ProcessClass(INamedTypeSymbol classSymbol)
        {
            var className = classSymbol.Name;
            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            if (namespaceName != null)
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {className} DeepClone(ObjectTreeWalker.CloningContext? ctx = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            ctx ??= new ObjectTreeWalker.CloningContext();");
            sb.AppendLine($"            if (ctx.TryGetClone(this, out var existingClone)) return ({className})existingClone!;");
            sb.AppendLine($"            var clone = new {className}();");
            sb.AppendLine("            ctx.RecordClone(this, clone);");

            foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                if (member.SetMethod != null && member.SetMethod.DeclaredAccessibility == Accessibility.Public)
                {
                    sb.AppendLine($"            clone.{member.Name} = this.{member.Name}; // simple assign for now");
                }
            }

            sb.AppendLine("            return clone;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (namespaceName != null)
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }
    }
}
