#pragma warning disable CS1591
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ObjectTreeWalker.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class ObjectWalkerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            var compilationAndClasses = context.CompilationProvider.Combine(provider.Collect());

            context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            foreach (var attributeListSyntax in classDeclaration.AttributeLists)
            {
                foreach (var attributeSyntax in attributeListSyntax.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is IMethodSymbol attributeSymbol)
                    {
                        if (attributeSymbol.ContainingType.ToDisplayString() == "ObjectTreeWalker.ObjectWalkableAttribute")
                        {
                            return classDeclaration;
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> classes, SourceProductionContext context)
        {
            if (classes.IsDefaultOrEmpty) return;

            var distinctClasses = classes.Where(c => c != null).Distinct();

            foreach (var classDeclaration in distinctClasses)
            {
                var semanticModel = compilation.GetSemanticModel(classDeclaration!.SyntaxTree);
                var symbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                if (symbol == null) continue;

                var source = ProcessClass(symbol);
                context.AddSource($"{symbol.Name}_Walk.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string ProcessClass(INamedTypeSymbol classSymbol)
        {
            var className = classSymbol.Name;
            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            if (namespaceName != null)
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        public void Walk(ObjectTreeWalker.IObjectVisitor visitor)");
            sb.AppendLine("        {");
            sb.AppendLine("            var queue = ObjectTreeWalker.CollectionPools.RentBfsQueue();");
            sb.AppendLine("            var visited = ObjectTreeWalker.CollectionPools.RentVisitedDictionary();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                queue.Enqueue(this);");
            sb.AppendLine("                visited[this] = null!;");
            sb.AppendLine("                while (queue.Count > 0)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var current = queue.Dequeue();");
            sb.AppendLine("                    visitor.Visit(current);");
            sb.AppendLine($"                    if (current is {className} typedCurrent)");
            sb.AppendLine("                    {");

            foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                if (member.GetMethod != null && member.GetMethod.DeclaredAccessibility == Accessibility.Public && !member.Type.IsValueType && member.Type.SpecialType != SpecialType.System_String)
                {
                    sb.AppendLine($"                        if (typedCurrent.{member.Name} != null && !visited.ContainsKey(typedCurrent.{member.Name}))");
                    sb.AppendLine("                        {");
                    sb.AppendLine($"                            visited[typedCurrent.{member.Name}] = null!;");
                    sb.AppendLine($"                            queue.Enqueue(typedCurrent.{member.Name});");
                    sb.AppendLine("                        }");
                }
            }

            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                ObjectTreeWalker.CollectionPools.ReturnBfsQueue(queue);");
            sb.AppendLine("                ObjectTreeWalker.CollectionPools.ReturnVisitedDictionary(visited);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (namespaceName != null)
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }
    }
}
