repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-xml
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
